### ISSUE TITLE
4.26 build error

### ISSUE THREAD

**Issue by RichardsATcn** [Lynnvon/RawInputPluginForUE4#3]
[5/7] UE4Editor-RawInput.lib
      正在创建库 G:\Unreal Projects\COM_Test\Plugins\RawInputPluginForUE4.26\HostProject\Plugins\RawInput\Intermediate\Build\Win64\UE4Editor\Development\RawInput\UE4Editor-RawInput.lib 和对象 G:\Unreal Projects\COM_Test\Plugins\RawInputPluginForUE4.26\HostProject\Plugins\RawInput\Intermediate\Build\Win64\UE4Editor\Development\RawInput\UE4Editor-RawInput.exp
    [6/7] UE4Editor-RawInput.dll
      正在创建库 G:\Unreal Projects\COM_Test\Plugins\RawInputPluginForUE4.26\HostProject\Plugins\RawInput\Intermediate\Build\Win64\UE4Editor\Development\RawInput\UE4Editor-RawInput.suppressed.lib 和对象 G:\Unreal Projects\COM_Test\Plugins\RawInputPluginForUE4.26\HostProject\Plugins\RawInput\Intermediate\Build\Win64\UE4Editor\Development\RawInput\UE4Editor-RawInput.suppressed.exp
    Module.RawInput.cpp.obj : error LNK2019: 无法解析的外部符号 "__declspec(dllimport) public: __cdecl UDeveloperSettings::UDeveloperSettings(class FObjectInitializer const &)" (__imp_??0UDeveloperSettings@@QEAA@AEBVFObjectInitializer@@@Z) ，函数 "public: __cdecl URawInputSettings::URawInputSettings(class FObjectInitializer const &)" (??0URawInputSettings@@QEAA@AEBVFObjectInitializer@@@Z) 中引用了该符号
    Module.RawInput.gen.cpp.obj : error LNK2001: 无法解析的外部符号 "__declspec(dllimport) public: __cdecl UDeveloperSettings::UDeveloperSettings(class FObjectInitializer const &)" (__imp_??0UDeveloperSettings@@QEAA@AEBVFObjectInitializer@@@Z)
    Module.RawInput.cpp.obj : error LNK2019: 无法解析的外部符号 "__declspec(dllimport) public: virtual __cdecl UDeveloperSettings::~UDeveloperSettings(void)" (__imp_??1UDeveloperSettings@@UEAA@XZ)，函数 "public: virtual __cdecl URawInputSettings::~URawInputSettings(void)" (??1URawInputSettings@@UEAA@XZ) 中引用了该符号
    Module.RawInput.gen.cpp.obj : error LNK2001: 无法解析的外部符号 "__declspec(dllimport) public: virtual __cdecl UDeveloperSettings::~UDeveloperSettings(void)" (__imp_??1UDeveloperSettings@@UEAA@XZ)
    Module.RawInput.cpp.obj : error LNK2001: 无法解析的外部符号 "public: virtual class FName __cdecl UDeveloperSettings::GetContainerName(void)const " (?GetContainerName@UDeveloperSettings@@UEBA?AVFName@@XZ)
    Module.RawInput.gen.cpp.obj : error LNK2001: 无法解析的外部符号 "public: virtual class FName __cdecl UDeveloperSettings::GetContainerName(void)const " (?GetContainerName@UDeveloperSettings@@UEBA?AVFName@@XZ)
    Module.RawInput.cpp.obj : error LNK2001: 无法解析的外部符号 "public: virtual class TSharedPtr<class SWidget,0> __cdecl UDeveloperSettings::GetCustomSettingsWidget(void)const " (?GetCustomSettingsWidget@UDeveloperSettings@@UEBA?AV?$TSharedPtr@VSWidget@@$0A@@@XZ)
    Module.RawInput.gen.cpp.obj : error LNK2001: 无法解析的外部符号 "public: virtual class TSharedPtr<class SWidget,0> __cdecl UDeveloperSettings::GetCustomSettingsWidget(void)const " (?GetCustomSettingsWidget@UDeveloperSettings@@UEBA?AV?$TSharedPtr@VSWidget@@$0A@@@XZ)
    Module.RawInput.cpp.obj : error LNK2001: 无法解析的外部符号 "public: virtual class FText __cdecl UDeveloperSettings::GetSectionDescription(void)const " (?GetSectionDescription@UDeveloperSettings@@UEBA?AVFText@@XZ)
    Module.RawInput.gen.cpp.obj : error LNK2001: 无法解析的外部符号 "public: virtual class FText __cdecl UDeveloperSettings::GetSectionDescription(void)const " (?GetSectionDescription@UDeveloperSettings@@UEBA?AVFText@@XZ)
    Module.RawInput.cpp.obj : error LNK2001: 无法解析的外部符号 "public: virtual class FName __cdecl UDeveloperSettings::GetSectionName(void)const " (?GetSectionName@UDeveloperSettings@@UEBA?AVFName@@XZ)
    Module.RawInput.gen.cpp.obj : error LNK2001: 无法解析的外部符号 "public: virtual class FName __cdecl UDeveloperSettings::GetSectionName(void)const " (?GetSectionName@UDeveloperSettings@@UEBA?AVFName@@XZ)
    Module.RawInput.cpp.obj : error LNK2001: 无法解析的外部符号 "public: virtual void __cdecl UDeveloperSettings::PostEditChangeProperty(struct FPropertyChangedEvent &)" (?PostEditChangeProperty@UDeveloperSettings@@UEAAXAEAUFPropertyChangedEvent@@@Z)
    Module.RawInput.gen.cpp.obj : error LNK2001: 无法解析的外部符号 "public: virtual void __cdecl UDeveloperSettings::PostEditChangeProperty(struct FPropertyChangedEvent &)" (?PostEditChangeProperty@UDeveloperSettings@@UEAAXAEAUFPropertyCha    Module.RawInput.gen.cpp.obj : error LNK2001: 无法解析的外部符号 "public: virtual bool __cdecl UDeveloperSettings::SupportsAutoRegistration(void)const " (?SupportsAutoRegistration@UDeveloperSettings@@UEBA_NXZ)
 __cdecl UDeveloperSettings::StaticClass(void)" (__imp_?StaticClass@UDeveloperSettings@@SAPEAVUClass@@XZ)，函数 "private: static class UClass * __cdecl URawInputSettings::GetPrivateStaticClass(void)" (?GetPrivateStaticClass@URawInputSettings@@CAPEAVUClass@@XZ) 中引用了该符号
      已定义且可能匹配的符号上的提示:
        "__declspec(dllimport) public: static class UClass * __cdecl UObject::StaticClass(void)" (__imp_?StaticClass@UObject@@SAPEAVUClass@@XZ)
    Module.RawInput.gen.cpp.obj : error LNK2019: 无法解析的外部符号 "__declspec(dllimport) public: __cdecl UDeveloperSettings::UDeveloperSettings(class FVTableHelper &)" (__imp_??0UDeveloperSettings@@QEAA@AEAVFVTableHelper@@@Z)，函数 "public: __cdecl URawInputSettings::URawInputSettings(class FVTableHelper &)" (??0URawInputSettings@@QEAA@AEAVFVTableHelper@@@Z) 中引用了该符号
    Module.RawInput.gen.cpp.obj : error LNK2019: 无法解析的外部符号 "__declspec(dllimport) class UClass * __cdecl Z_Construct_UClass_UDeveloperSettings(void)" (__imp_?Z_Construct_UClass_UDeveloperSettings@@YAPEAVUClass@@XZ)，函数 "void __cdecl `dynamic initializer for 'public: static class UObject * (__cdecl*const * const Z_Construct_UClass_URawInputSettings_Statics::DependentSingletons)(void)''(void)" (??__E?DependentSingletons@Z_Construct_UClass_URawInputSettings_Statics@@2QBQ6APEAVUObject@@XZB@@YAXXZ) 中引用了该符号
    G:\Unreal Projects\COM_Test\Plugins\RawInputPluginForUE4.26\HostProject\Plugins\RawInput\Binaries\Win64\UE4Editor-RawInput.dll : fatal error LNK1120: 11 个无法解析的外部命令
Took 29.656961s to run UnrealBuildTool.exe, ExitCode=6
UnrealBuildTool failed. See log for more details. (C:\Users\Bluebuger\AppData\Roaming\Unreal Engine\AutomationTool\Logs\F+Program+Files+Epic+Games+UE_4.26\UBT-UE4Editor-Win64-Development.txt)
AutomationTool exiting with ExitCode=6 (6)
BUILD FAILED

**Comment by Lynnvon** [comment]
这是缺少了模块引入，在build.cs中添加DeveloperSettings的引入，PrivateDependencyModuleNames.AddRange(
				new string[]
				{
					"InputDevice",
					"DeveloperSettings"
				}
			);

**Comment by RichardsATcn** [comment]
感谢感谢
